### ISSUE TITLE
feature/event-page has type error on the reducer

### ISSUE THREAD

**Issue by CrispyBacon1999** [orange-alliance/toa-react#31]
No clue why it exists, just kind of showed up and branch can't be built for SSR due to this.

Error is at https://github.com/orange-alliance/toa-react/blob/feature/event-page/shared/stores/Reducer.ts#L36

**Comment by kyle-flynn** [comment]
https://github.com/orange-alliance/toa-react/blob/3a099e73b9b75d6fef3305b8eb9d2244861702f3/shared/stores/Reducer.ts#L95

Essentially this is because Redux isn't actually built to handle OOP like we're doing... However, we still use it this way. You can't update the property inside of the object. If this doesn't force a page update, you might have to do something like this:
```const newEvent: Event = new Event.fromJSON(state.currentEvent);
newEvent.rankings = action.payload.rankings;```
